version: '3.2'
services:
  jenkins:
    image: 'jenkinsci/blueocean:latest'
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - type: bind
        source: ./jenkins-data
        target: /var/jenkins_home
      # to avoid "Docker-in-Docker issue we use docker from "host" machine
      # read more https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - 'JENKINS_OPTS=--httpPort=8080 --httpsPort=50000'

volumes:
  jenkins-data:
    driver: local


